# coding: utf-8
# frozen_string_literal: false

# Copyright Ayumu Nojima (野島 歩) and Martin J. Dürst (duerst@it.aoyama.ac.jp)

# This file, the companion file tables.rb (autogenerated), and the module,
# constants, and method defined herein are part of the implementation of the
# built-in String class, not part of the standard library. They should
# therefore never be gemified. They implement the methods
# String#unicode_normalize, String#unicode_normalize!, and String#unicode_normalized?.
#
# They are placed here because they are written in Ruby. They are loaded on
# demand when any of the three methods mentioned above is executed for the
# first time. This reduces the memory footprint and startup time for scripts
# and applications that do not use those methods.
#
# The name and even the existence of the module UnicodeNormalize and all of its
# content are purely an implementation detail, and should not be exposed in
# any test or spec or otherwise.

require_relative 'tables'

# :stopdoc:
module UnicodeNormalize  # :nodoc:
  ## Constants For Hangul
  # for details such as the meaning of the identifiers below, please see
  # https://www.unicode.org/versions/Unicode16.0.0/core-spec/chapter-3/#G24646
  SBASE = 0xAC00
  LBASE = 0x1100
  VBASE = 0x1161
  TBASE = 0x11A7
  LCOUNT = 19
  VCOUNT = 21
  TCOUNT = 28
  NCOUNT = VCOUNT * TCOUNT # 588
  SCOUNT = LCOUNT * NCOUNT # 11172

  SLAST = SBASE + SCOUNT - 1  # U+D7A3
  LLAST = LBASE + LCOUNT - 1  # U+1112
  VLAST = VBASE + VCOUNT - 1  # U+1175
  TLAST = TBASE + TCOUNT - 1  # U+11C2
  TFIRST = TBASE + 1          # U+11A8

  # Unicode-based encodings (except UTF-8)
  UNICODE_ENCODINGS = [Encoding::UTF_16BE, Encoding::UTF_16LE, Encoding::UTF_32BE, Encoding::UTF_32LE,
                       Encoding::GB18030, Encoding::UCS_2BE, Encoding::UCS_4BE]

  ## Hangul Algorithm
  def self.hangul_decomp_one(target)
    syllable_index = target.ord - SBASE
    return target if syllable_index < 0 || syllable_index >= SCOUNT
    l = LBASE + syllable_index / NCOUNT
    v = VBASE + (syllable_index % NCOUNT) / TCOUNT
    t = TBASE + syllable_index % TCOUNT
    (t==TBASE ? [l, v] : [l, v, t]).pack('U*') + target[1..-1]
  end

  def self.hangul_comp_one(a, b)
    a_ord = a.ord
    b_ord = b.ord

    # (L, V) -> LV
    if (LBASE..LLAST).cover?(a_ord) && (VBASE..VLAST).cover?(b_ord)
      l = a_ord - LBASE
      v = b_ord - VBASE
      lv = l * NCOUNT + v * TCOUNT
      codepoint = SBASE + lv # Codepoint of the composed Hangul
      return codepoint.chr(Encoding::UTF_8)
    end

    # (LV, T) -> LVT
    if (SBASE..SLAST).cover?(a_ord)
      s = a_ord - SBASE
      if (s % TCOUNT) == 0 && (TFIRST..TLAST).cover?(b_ord)
        composed = a_ord + (b_ord - TBASE)
        return composed.chr(Encoding::UTF_8)
      end
    end

    nil
  end

  def self.to_nfd_arr(string)
    decomposed_arr = string.each_char.flat_map { decompose_one(it) }
    canonical_ordering(decomposed_arr)
  end

  def self.to_nfkd_arr(string)
    kompatibled_arr = string.each_char.flat_map { kompatible_one(it) }
    decomposed_arr = kompatibled_arr.each.flat_map { decompose_one(it) }
    canonical_ordering(decomposed_arr)
  end

  def self.to_nfkc_arr(string)
    arr = to_nfkd_arr(string)
    recompose_arr(arr)
  end

  def self.to_nfc_arr(string)
    nfd_arr = to_nfd_arr(string)
    recompose_arr(nfd_arr)
  end

  def self.recompose_arr(nfd_arr)
    result = []
    last_starter_idx = nil

    nfd_arr.each do |char|
      current_cc = COMBINING_CLASS_TABLE[char]
      if result.empty?
        result << char
        last_starter_idx = 0
        next
      end

      combined = false
      if last_starter_idx
        unless blocked?(result, last_starter_idx, current_cc)
          starter = result[last_starter_idx]

          # Try hangul comp
          new_cp = hangul_comp_one(starter, char)
          # Try to compose with a starter
          unless new_cp
            pair = starter + char
            new_cp = COMPOSITION_TABLE[pair]
          end

          if new_cp
            result[last_starter_idx] = new_cp
            combined = true
          end
        end
      end

      unless combined
        result << char
        last_starter_idx = result.size - 1 if current_cc == 0
      end
    end

    result
  end

  def self.blocked?(result, last_starter_idx, new_char_cc)
    (last_starter_idx+1..result.size-1).each do |idx|
      cc = COMBINING_CLASS_TABLE[result[idx]]
      return true if cc >= new_char_cc
    end

    false
  end

  def self.decompose_one(target)
    h = hangul_decomp_one(target)
    if h.size > 1
      return h.each_char.flat_map { decompose_one(it) }
    end

    if mapped = DECOMPOSITION_TABLE[target]
      mapped.each_char.flat_map { decompose_one(it) }
    else
      [target]
    end
  end

  def self.kompatible_one(target)
    if mapped = KOMPATIBLE_TABLE[target]
      mapped
    else
      target
    end
  end

  # https://www.unicode.org/versions/Unicode16.0.0/core-spec/chapter-3/#G49591
  def self.canonical_ordering(arr)
    i = 0
    while i < arr.size - 1
      ccc1 = COMBINING_CLASS_TABLE[arr[i]]
      ccc2 = COMBINING_CLASS_TABLE[arr[i+1]]

      if ccc1 > ccc2 && ccc2 != 0
        arr[i], arr[i+1] = arr[i+1], arr[i]
        i -= 1 if i > 0
      else
        i += 1
      end
    end
    arr
  end

  def self.normalize(string, form = :nfc)
    encoding = string.encoding
    case encoding
    when Encoding::UTF_8
      return string if string.ascii_only?

      case form
      when :nfc then
        to_nfc_arr(string).join
      when :nfd then
        to_nfd_arr(string).join
      when :nfkc then
        to_nfkc_arr(string).join
      when :nfkd then
        to_nfkd_arr(string).join
      else
        raise ArgumentError, "Invalid normalization form #{form}."
      end
    when Encoding::US_ASCII
      string
    when *UNICODE_ENCODINGS
      normalize(string.encode(Encoding::UTF_8), form).encode(encoding)
    else
      raise Encoding::CompatibilityError, "Unicode Normalization not appropriate for #{encoding}"
    end
  end

  def self.normalized?(string, form = :nfc)
    encoding = string.encoding
    case encoding
    when Encoding::UTF_8
      return true if string.ascii_only?

      case form
      when :nfc then
        return to_nfc_arr(string).join == string
      when :nfd then
        return to_nfd_arr(string).join == string
      when :nfkc then
        return to_nfkc_arr(string).join == string
      when :nfkd then
        return to_nfkd_arr(string).join == string
      else
        raise ArgumentError, "Invalid normalization form #{form}."
      end
    when Encoding::US_ASCII
      true
    when *UNICODE_ENCODINGS
      normalized? string.encode(Encoding::UTF_8), form
    else
      raise Encoding::CompatibilityError, "Unicode Normalization not appropriate for #{encoding}"
    end
  end

  # TODO: Implement quick_check?
  def self.quick_check?(string, method, table, form = :nfc)
    return false if canonical_ordering_one(hangul_decomp_one(string)) != string

    has_maybe = false
    string.each_char do |char|
      qc = table[char]
      return false if qc == 'N'
      has_maybe ||= true if qc == 'M'
    end

    if has_maybe
      changed_string = send(method, string) # FIXME
      return (changed_string == string)
    else
      true
    end
  end
end # module
